#!/bin/bash

echo "$@" | socat - TCP:host.docker.internal:${XDGOPEN_TCP_PORT}

#echo "$@" | socat - TCP:127.0.0.1:${XDGOPEN_TCP_PORT}

#echo "$@" | socat - "UNIX-CLIENT:/Users/ospost/var/run/$(id --user)/xdg-open-server/socket"
